#!/bin/sh

# Usage:
# To bootstrap your machine with piku:
# 
# ssh root@YOUR-MACHINE-IP
# ./piku-bootstrap install

# exit on error
set -e

PBD=${PIKU_BOOTSTRAP_DIR:-~/.piku-bootstrap}
VENV="${PBD}/virtualenv"
REPO="${PBD}/piku-bootstrap"
VIRTUALENV_VERSION="20.0.0"
LOG="${PBD}/install.log"

main() {
  # print a message if this is a first time run
  if [ ! -d "${PBD}" ]; then
    echo "Looks like this is your first time running piku-bootstrap."
    echo "This script will self-install dependencies into ${PBD} now."
    echo "Hit enter to continue or ctrl-C to abort."
    read discarded
    echo
  fi

  # ensure we have a dir
  mkdir -p "${PBD}"

  # ensure we have the piku repo checked out
  if [ ! -d "${REPO}" ]; then
    echo " #> Piku Bootstrap repo not found. Installing it into ${REPO}."
    git clone https://github.com/angordeyev/piku-bootstrap "${REPO}"
  fi

  if [ "$1" = "" ]
  then
    echo
    echo "Usage:"
    echo "       `basename $0` install"
    echo
    echo "Notes:"
    echo
    echo " ** WARNING **"
    echo " This script installs software and makes changes on this server."
    echo " Only use a freshly provisioned server which you do not mind"
    echo " being modified and reconfigured."
    echo
    echo " See https://github.com/piku/piku for details."
    echo
  else
    case "$1" in
      first-run)
        echo
        echo " #> Success!"
        echo
        echo "The piku-bootstrap command is now installed in the current folder."
        echo "Run './piku-bootstrap' with no arguments for help."
        echo "To install Piku on this server for the first time run './piku-bootstrap install'."
        echo ""
        ;;
      install)
        ./.piku-bootstrap/piku-bootstrap/scripts/install.sh
        ;;
    esac
  fi
}

main "$@"
