---
- hosts: all
  become: yes
  vars:
    homedir: /home/{{ piku_user | default('piku', true)}}/
    user: "{{ piku_user | default('piku', true)}}"
    ssh_user: "{{ lookup('env', 'SUDO_USER') | default('root') }}"

- hosts: all
  become: yes
  tasks:

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
      when: nginx_config_installed is changed

    - name: Get incron config
      get_url:
        url: https://raw.githubusercontent.com/piku/piku/master/incron.dist
        dest: /etc/incron.d/piku
      register: incron_config_installed

    - name: Restart incron service
      service:
        name: incron
        state: restarted
      when: incron_config_installed is changed
